[promgraf]
promgraf1 ansible_host=ip1 ansible_user=ec2-user ansible_private_key_file=pem_file

[targets]
target1 ansible_host=ip2 ansible_user=ec2-user ansible_private_key_file=pem_file
target2 ansible_host=ip3 ansible_user=ec2-user ansible_private_key_file=pem_file